export const PAGE_NAMES = {
  INDEX: 'INDEX',
  HELPERS: {
    PORTFOLIO_REBALANCING: 'HELPERS__PORTFOLIO_REBALANCING',
  },
  CALCULATORS: {
    SP500: 'CALCULATORS__SP500',
    FINANCIAL_FREEDOM: 'CALCULATORS__FINANCIAL_FREEDOM',
  },
}
